use std::{
    collections::{HashMap, HashSet},
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, anyhow, bail};
use chrono::Utc;

use crate::{
    exiftool,
    hashing::sha256_file,
    models::{ApplyLog, Confidence, ExecutionPlan},
    site,
};

pub fn run(
    plan_path: &Path,
    raw_out: &Path,
    update_site: bool,
    include_low_confidence: bool,
    overwrite_existing: bool,
) -> Result<ApplyLog> {
    let started_at = Utc::now();
    let plan_path = dunce::canonicalize(plan_path)
        .with_context(|| format!("plan does not exist: {}", plan_path.display()))?;
    let plan_dir = plan_path
        .parent()
        .ok_or_else(|| anyhow!("plan has no parent directory"))?;
    let plan: ExecutionPlan = serde_json::from_slice(&fs::read(&plan_path)?)?;
    if plan.schema != "gpslog.geotag-plan/v1" {
        bail!("unsupported plan schema: {}", plan.schema);
    }
    if plan.tool_version != env!("CARGO_PKG_VERSION") {
        bail!(
            "plan was generated by gpslog-geotag {}, current version is {}; regenerate preview",
            plan.tool_version,
            env!("CARGO_PKG_VERSION")
        );
    }
    validate_plan_paths(&plan)?;
    preflight_hashes(&plan)?;

    let raw_input = dunce::canonicalize(&plan.parameters.raw_dir)?;
    let raw_out = absolute_path(raw_out)?;
    if raw_out == raw_input || raw_out.starts_with(&raw_input) {
        bail!("--raw-out must differ from and must not be inside the input RAW directory");
    }
    fs::create_dir_all(&raw_out)?;
    let raw_out = dunce::canonicalize(raw_out)?;
    if raw_out == raw_input || raw_out.starts_with(&raw_input) {
        bail!("--raw-out resolves inside the input RAW directory");
    }

    let executable = exiftool::ensure_exiftool()?;
    let actual_version = exiftool::version(&executable)?;
    if actual_version != plan.exiftool_version {
        bail!(
            "ExifTool version changed from {} to {actual_version}; regenerate preview",
            plan.exiftool_version
        );
    }

    let mut log = ApplyLog {
        schema: "gpslog.apply-log/v1".into(),
        started_at,
        finished_at: started_at,
        plan_path: plan_path.clone(),
        raw_out: raw_out.clone(),
        raw_outputs: Vec::new(),
        site_files_updated: Vec::new(),
        site_transaction_succeeded: None,
        warnings: Vec::new(),
    };
    write_log(plan_dir, &mut log)?;

    for photo in &plan.photos {
        let overwrite = plan.parameters.overwrite_existing || overwrite_existing;
        let eligible = photo.confidence == Confidence::High
            || (photo.confidence == Confidence::Low
                && (plan.parameters.include_low_confidence || include_low_confidence));
        let unresolved_existing_conflict =
            has_unresolved_existing_conflict(photo.existing_raw_gps, &photo.warnings, overwrite);
        if !eligible
            || photo.location.is_none()
            || photo.site_mapping.starts_with("conflict:")
            || unresolved_existing_conflict
        {
            continue;
        }
        let destination = raw_out.join(&photo.output_file_name);
        if destination.exists() {
            write_log(plan_dir, &mut log)?;
            bail!(
                "RAW output already exists, refusing to overwrite: {}",
                destination.display()
            );
        }
        let copy_result = (|| -> Result<()> {
            fs::copy(&photo.raw_path, &destination)?;
            fs::File::options()
                .write(true)
                .open(&destination)?
                .sync_all()?;
            exiftool::write_location(&executable, &destination, photo.location.as_ref().unwrap())?;
            exiftool::verify_location(&executable, &destination, photo.location.as_ref().unwrap())?;
            let original_after = sha256_file(&photo.raw_path)?;
            if original_after != photo.raw_sha256 {
                bail!(
                    "original RAW changed while applying: {}",
                    photo.raw_path.display()
                );
            }
            Ok(())
        })();
        if let Err(error) = copy_result {
            if destination.exists() {
                let _ = fs::remove_file(&destination);
            }
            log.warnings
                .push(format!("failed {}: {error:#}", photo.raw_path.display()));
            write_log(plan_dir, &mut log)?;
            return Err(error);
        }
        log.raw_outputs.push(destination);
    }

    if update_site {
        match update_site_transaction(
            &plan,
            plan_dir,
            include_low_confidence,
            overwrite_existing,
            &mut log,
        ) {
            Ok(()) => log.site_transaction_succeeded = Some(true),
            Err(error) => {
                log.site_transaction_succeeded = Some(false);
                log.warnings.push(format!(
                    "site transaction failed and was rolled back: {error:#}"
                ));
                write_log(plan_dir, &mut log)?;
                return Err(error);
            }
        }
    }
    write_log(plan_dir, &mut log)?;
    Ok(log)
}

fn preflight_hashes(plan: &ExecutionPlan) -> Result<()> {
    if sha256_file(&plan.parameters.track)? != plan.track_sha256 {
        bail!("track hash changed after preview; regenerate preview");
    }
    for photo in &plan.photos {
        if sha256_file(&photo.raw_path)? != photo.raw_sha256 {
            bail!("RAW changed after preview: {}", photo.raw_path.display());
        }
        if let (Some(path), Some(expected)) = (&photo.site_json_path, &photo.site_json_sha256)
            && sha256_file(path)? != *expected
        {
            bail!("site JSON changed after preview: {}", path.display());
        }
    }
    Ok(())
}

fn validate_plan_paths(plan: &ExecutionPlan) -> Result<()> {
    if !plan.parameters.track.is_absolute()
        || !plan.parameters.raw_dir.is_absolute()
        || !plan.parameters.site_repo.is_absolute()
        || !plan.parameters.album.is_absolute()
    {
        bail!("plan input paths must be absolute; regenerate preview");
    }
    let raw_root = dunce::canonicalize(&plan.parameters.raw_dir)?;
    let site_repo = dunce::canonicalize(&plan.parameters.site_repo)?;
    let photos_root = dunce::canonicalize(site_repo.join("content").join("photos"))?;
    let album = dunce::canonicalize(&plan.parameters.album)?;
    if album == photos_root || !album.starts_with(&photos_root) {
        bail!("plan album escaped site content/photos");
    }

    let mut output_names = HashMap::new();
    let mut site_targets = HashMap::new();
    for photo in &plan.photos {
        if !photo.raw_path.is_absolute() {
            bail!("plan RAW paths must be absolute");
        }
        let raw_path = dunce::canonicalize(&photo.raw_path)?;
        if !raw_path.starts_with(&raw_root)
            || !raw_path.is_file()
            || !raw_path
                .extension()
                .is_some_and(|value| value.eq_ignore_ascii_case("nef"))
        {
            bail!(
                "plan RAW escaped the input directory: {}",
                raw_path.display()
            );
        }
        let output_path = Path::new(&photo.output_file_name);
        let mut components = output_path.components();
        if !matches!(components.next(), Some(std::path::Component::Normal(_)))
            || components.next().is_some()
            || raw_path.file_name() != Some(output_path.as_os_str())
        {
            bail!("invalid RAW output file name: {}", photo.output_file_name);
        }
        let marked_conflict = photo.site_mapping.starts_with("conflict:");
        if let Some(previous_marked_conflict) =
            output_names.insert(photo.output_file_name.to_lowercase(), marked_conflict)
            && !(previous_marked_conflict && marked_conflict)
        {
            bail!("multiple executable plan entries use the same RAW output file name");
        }

        match (&photo.site_json_path, &photo.site_json_sha256) {
            (Some(path), Some(_)) => {
                if !path.is_absolute() {
                    bail!("plan site JSON paths must be absolute");
                }
                let site_path = dunce::canonicalize(path)?;
                if site_path.parent() != Some(album.as_path())
                    || !site_path
                        .extension()
                        .is_some_and(|value| value.eq_ignore_ascii_case("json"))
                {
                    bail!(
                        "plan site JSON escaped the selected album: {}",
                        site_path.display()
                    );
                }
                let marked_conflict = photo.site_mapping.starts_with("conflict:");
                if let Some(previous_marked_conflict) =
                    site_targets.insert(site_path, marked_conflict)
                    && !(previous_marked_conflict && marked_conflict)
                {
                    bail!("multiple executable plan entries target the same site JSON");
                }
            }
            (None, None) => {}
            _ => bail!("plan site JSON path/hash pair is incomplete"),
        }
    }
    Ok(())
}

fn update_site_transaction(
    plan: &ExecutionPlan,
    plan_dir: &Path,
    include_low_confidence: bool,
    overwrite_existing: bool,
    log: &mut ApplyLog,
) -> Result<()> {
    let site_repo = dunce::canonicalize(&plan.parameters.site_repo)?;
    let timestamp = Utc::now().format("%Y%m%dT%H%M%SZ").to_string();
    let backup_root = plan_dir.join("backups").join(timestamp).join("site");
    fs::create_dir_all(&backup_root)?;
    let mut snapshot_paths = site::list_photo_json(&site_repo)?;
    let china_json = site_repo.join("data").join("china.json");
    if china_json.exists() {
        snapshot_paths.push(china_json);
    }
    let snapshots = snapshot_files(&site_repo, &backup_root, &snapshot_paths)?;

    let transaction = (|| -> Result<()> {
        let mut updated = HashSet::new();
        for photo in &plan.photos {
            let overwrite = plan.parameters.overwrite_existing || overwrite_existing;
            let confidence_eligible = photo.confidence == Confidence::High
                || (photo.confidence == Confidence::Low
                    && (plan.parameters.include_low_confidence || include_low_confidence));
            let unresolved_existing_conflict = has_unresolved_existing_conflict(
                photo.existing_raw_gps,
                &photo.warnings,
                overwrite,
            );
            if !confidence_eligible
                || photo.location.is_none()
                || photo.site_mapping.starts_with("conflict:")
                || unresolved_existing_conflict
            {
                continue;
            }
            let Some(path) = &photo.site_json_path else {
                continue;
            };
            if site::apply_location(path, photo.location.as_ref().unwrap(), overwrite)? {
                updated.insert(path.clone());
            }
        }
        run_site_command(&site_repo, "pnpm.cmd", &["locations:backfill"])?;
        run_site_command(&site_repo, "node.exe", &["scripts/generate-map-data.js"])?;
        run_site_command(&site_repo, "pnpm.cmd", &["maps:validate"])?;
        log.site_files_updated.extend(updated);
        Ok(())
    })();
    if let Err(error) = transaction {
        restore_snapshot(&snapshots)?;
        return Err(error);
    }
    Ok(())
}

fn snapshot_files(
    site_repo: &Path,
    backup_root: &Path,
    paths: &[PathBuf],
) -> Result<Vec<(PathBuf, PathBuf)>> {
    let mut snapshots = Vec::with_capacity(paths.len());
    for path in paths {
        let relative = path
            .strip_prefix(site_repo)
            .with_context(|| format!("site path escaped repository: {}", path.display()))?;
        let backup = backup_root.join(relative);
        if let Some(parent) = backup.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(path, &backup)?;
        fs::File::options().write(true).open(&backup)?.sync_all()?;
        snapshots.push((path.clone(), backup));
    }
    Ok(snapshots)
}

fn restore_snapshot(snapshots: &[(PathBuf, PathBuf)]) -> Result<()> {
    for (target, backup) in snapshots {
        fs::copy(backup, target)?;
        fs::File::options().write(true).open(target)?.sync_all()?;
    }
    Ok(())
}

fn run_site_command(directory: &Path, program: &str, arguments: &[&str]) -> Result<()> {
    let output = Command::new(program)
        .args(arguments)
        .current_dir(directory)
        .output()
        .with_context(|| format!("could not start {program}"))?;
    if !output.status.success() {
        bail!(
            "{} {} failed:\n{}\n{}",
            program,
            arguments.join(" "),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
    Ok(())
}

fn write_log(plan_dir: &Path, log: &mut ApplyLog) -> Result<()> {
    log.finished_at = Utc::now();
    let path = plan_dir.join("apply-log.json");
    let mut file = fs::File::create(path)?;
    serde_json::to_writer_pretty(&mut file, log)?;
    file.write_all(b"\n")?;
    file.sync_all()?;
    Ok(())
}

fn absolute_path(path: &Path) -> Result<PathBuf> {
    Ok(if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()?.join(path)
    })
}

fn has_unresolved_existing_conflict(
    existing_raw_gps: bool,
    warnings: &[String],
    overwrite: bool,
) -> bool {
    !overwrite
        && (existing_raw_gps
            || warnings
                .iter()
                .any(|warning| warning.contains("site JSON already contains different GPS")))
}

#[cfg(test)]
mod tests {
    use chrono::TimeZone;

    use super::{has_unresolved_existing_conflict, validate_plan_paths};
    use crate::models::{Confidence, ExecutionPlan, PhotoPlan, PreviewParameters};

    #[test]
    fn existing_locations_are_skipped_unless_overwrite_is_explicit() {
        let site_warning = vec!["site JSON already contains different GPS coordinates".into()];
        assert!(has_unresolved_existing_conflict(true, &[], false));
        assert!(has_unresolved_existing_conflict(
            false,
            &site_warning,
            false
        ));
        assert!(!has_unresolved_existing_conflict(true, &site_warning, true));
        assert!(!has_unresolved_existing_conflict(false, &[], false));
    }

    #[test]
    fn plan_paths_cannot_escape_raw_or_selected_album() {
        let directory = tempfile::tempdir().unwrap();
        let raw_dir = directory.path().join("raw");
        let site_repo = directory.path().join("site");
        let album = site_repo.join("content/photos/album");
        std::fs::create_dir_all(&raw_dir).unwrap();
        std::fs::create_dir_all(&album).unwrap();
        let raw = raw_dir.join("a.NEF");
        let site_json = album.join("a.json");
        let track = directory.path().join("track.json");
        std::fs::write(&raw, b"raw").unwrap();
        std::fs::write(&site_json, b"{}").unwrap();
        std::fs::write(&track, b"{}").unwrap();
        let mut plan = ExecutionPlan {
            schema: "gpslog.geotag-plan/v1".into(),
            created_at: chrono::Utc.with_ymd_and_hms(2026, 8, 8, 0, 0, 0).unwrap(),
            tool_version: "1.0.0".into(),
            exiftool_version: "13.59".into(),
            parameters: PreviewParameters {
                track: dunce::canonicalize(track).unwrap(),
                raw_dir: dunce::canonicalize(raw_dir).unwrap(),
                site_repo: dunce::canonicalize(&site_repo).unwrap(),
                album: dunce::canonicalize(&album).unwrap(),
                timezone: "Asia/Shanghai".into(),
                clock_offset: "+00:00:00".into(),
                include_low_confidence: false,
                overwrite_existing: false,
            },
            track_sha256: "00".repeat(32),
            photos: vec![PhotoPlan {
                raw_path: dunce::canonicalize(raw).unwrap(),
                raw_sha256: "00".repeat(32),
                output_file_name: "a.NEF".into(),
                camera_time_source: None,
                camera_local_time: None,
                corrected_timestamp_utc: None,
                camera_model: None,
                existing_raw_gps: false,
                confidence: Confidence::Unmatched,
                bracket: None,
                location: None,
                site_json_path: Some(dunce::canonicalize(site_json).unwrap()),
                site_json_sha256: Some("00".repeat(32)),
                site_mapping: "exact RAW stem".into(),
                existing_site_location: false,
                eligible: false,
                warnings: Vec::new(),
            }],
        };
        assert!(validate_plan_paths(&plan).is_ok());

        plan.photos[0].output_file_name = "../escape.NEF".into();
        assert!(validate_plan_paths(&plan).is_err());
        plan.photos[0].output_file_name = "a.NEF".into();

        let outside = site_repo.join("content/photos/outside.json");
        std::fs::write(&outside, b"{}").unwrap();
        plan.photos[0].site_json_path = Some(dunce::canonicalize(outside).unwrap());
        assert!(validate_plan_paths(&plan).is_err());
    }
}
